config/routes.rb
Rails.application.routes.draw do
  root "cuisines#index"
  resources :order_items
  resources :cuisines, only: [:index, :show]
  resources :restaurants
  resources :items
  resources :orders
  resources :users
  resource :cart, only: [:show]
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get "/secretapology", to: "sessions#absolve", as: "absolve"
  get '/orders/:id/confirmation', to: 'orders#confirmation', as: 'confirmation'
  delete "/logout", to: "sessions#destroy", as: "logout"
  delete "/clearcart", to: "carts#destroy", as: "clear_cart"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :restaurants
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  def viewable
    "Order No. #{self.id}"
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates :quantity, numericality: {greater_than: 0}

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :cuisine
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
    has_many :orders, dependent: :destroy
    validates_presence_of :username
    validates_presence_of :address
    validates_presence_of :email
    validates_presence_of :phone_number
    # validates_uniqueness_of :phone_number
    validates_uniqueness_of :username

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if session[:order_id] && Order.find(session[:order_id]).exists?
      Order.find(session[:order_id])
    else
      order = Order.create(user_id: session[:user_id], status: false)
      session[:order_id] = order.id
      order
    end
  end

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      flash[:message] = "Please login or sign up to place an order" 
      redirect_to login_path
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end

  def destroy
    session.delete :order_id
    redirect_to cart_path
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

  def index
    @cuisines = Cuisine.all
  end

  def show 
    @cuisine = Cuisine.find(params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
   
    def index
        restaurant = Restaurant.find_by(id: params[:id])
        @items = Item.where(restaurant_id: restaurant)
    end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  
  def new 
  end

  def create
    @order = current_order
    @order_item = @order.order_items.new(item_params)
      if @order_item.valid?
          @order_item.save
          flash[:success] = "Item has been added to cart!"
          redirect_back(fallback_location: root_path)
    else 
      flash[:success] = "Please select at least one item"
      redirect_back(fallback_location: root_path)
    end
  end
  
  def show
    @order_item = OrderItem.find
  end

  def destroy
    @order_item = current_order.order_items.find(params[:id])
    @order_item.destroy
    redirect_to cart_path
  end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :item_id)
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_items = current_order.order_items
  end

  def confirmation
    @order = Order.find(params[:id])
    @order_items = current_order.order_items
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController   

  def index 
    @restaurants = Restaurant.all
  end

  def show 
    if session[:user_id]
      User.find(session[:user_id])
      @restaurant = Restaurant.find(params[:id])
      @order_item = current_order.order_items.new
    else
      flash[:message] = "Please login or sign up to place an order" 
      redirect_to login_path
    end
  end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ApplicationHelper

  def new
    if logged_in?
      redirect_to @current_user
    end
  end
#everytime we log in we create new user and order session
  def create
    session[:incorrect_count] ||= 0
    username = params[:username]
    password = params[:password]
    user = User.find_by(username: username)
      if user && user.authenticate(password)
        session[:user_id] = user.id
        order = Order.create(user_id: session[:user_id], status: false)
        session[:order_id] = order.id
        redirect_to root_path
      else
    flash[:message] = "Incorrect username or password. Please try again."
    session[:incorrect_count] += 1
      if session[:incorrect_count] >= 100
        session[:lockout] = "You have exceeded your number of login attempts!"
      end
    redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    session.delete(:order_id)
    redirect_to root_path
  end

  def absolve
    session[:lockout] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:message] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end
  
  def edit
    find_user
  end

  def update
    find_user
    if @user.update(user_params)
      flash[:message] = "Your account has been successfully updated."
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def show
    redirect_to login_path and return if !logged_in?

    if current_user.id != params[:id].to_i
      redirect_to current_user
    end

  end

  def destroy
    find_user
    @user.destroy
    session.delete :user_id
    flash[:notice] = "User deleted"
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation, :address, :email, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end    
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
 
end

app/views/cuisines/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
        <div class="card">
        <a href='/cuisines/1'><img class="card-img-top" src="https://images.unsplash.com/photo-1558985212-92c2ff0b56e7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80" alt="Sushi"></a>
        <div class="card-body">
          <h5 class="card-title">Japanese</h5>
          <p class="card-text">Japanese cuisine that is sure to tantalize your tastebuds.</p>
        </div>
      </div>

  <div class="card">
    <a href='/cuisines/2'><img class="card-img-top" src="https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1651&q=80" alt="Mexican food"></a>
    <div class="card-body">
      <h5 class="card-title">Mexican</h5>
      <p class="card-text">Tacos, quesadillas, pambazos, tamales, huaraches, alambres, al pastor. Need I say more?</p>
    </div>
  </div>

  <div class="card">
    <a href='/cuisines/3'><img class="card-img-top" src="https://images.unsplash.com/photo-1555196301-9acc011dfde4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="Cheeseburger"></a>
    <div class="card-body">
      <h5 class="card-title">American</h5>
      <p class="card-text">We've got you covered with the classics like burgers, fried chicken, hot dogs and pancakes.</p>
    </div>
  </div>
    </div>
    <div class="col-sm">
        <div class="card">
    <a href='/cuisines/4'><img class="card-img-top" src="https://images.unsplash.com/photo-1550303659-a777c03a27bd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80" alt="Chinese food"></a>
    <div class="card-body">
      <h5 class="card-title">Chinese</h5>
      <p class="card-text">Food that tastes just like Uncle used to make on the streets of Shanghai.</p>
    </div>
  </div>
  <div class="card">
    <a href='/cuisines/5'><img class="card-img-top" src="https://images.unsplash.com/photo-1517314626714-ac1b9a16515e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="Moroccan food"></a>
    <div class="card-body">
      <h5 class="card-title">Moroccan</h5>
      <p class="card-text">Moroccan cuisine is influenced by Morocco's interactions with other cultures over the centuries.</p>
    </div>
  </div>
  <div class="card">
  
    <a href='/cuisines/6'><img class="card-img-top" src="https://images.unsplash.com/photo-1432139555190-58524dae6a55?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1655&q=80" alt="Moroccan food"></a>
    <div class="card-body">
      <h5 class="card-title">French</h5>
      <p class="card-text">Exquisite, elegant and sophisticated dishes are not only for dining out. Be fancy from the comfort of home.</p>
    </div>
  </div>
    </div>
    <div class="col-sm">
        <div class="card">
    <a href='/cuisines/7'><img class="card-img-top" src="https://images.unsplash.com/photo-1441850605338-1b0b5a22e7b9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="Thai food"></a>
    <div class="card-body">
      <h5 class="card-title">Thai</h5>
      <p class="card-text">Dishes that display strong aromatic components and a spicy edge.</p>
    </div>
  </div>
  <div class="card">
    <a href='/cuisines/8'><img class="card-img-top" src="https://images.unsplash.com/photo-1498579150354-977475b7ea0b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="Italian food"></a>
    <div class="card-body">
      <h5 class="card-title">Italian</h5>
      <p class="card-text">More than just pizza and spaghetti. Explore the huge variety of Italian dishes and try something new!</p>
    </div>
  </div>
  <div class="card">
    <a href='/cuisines/9'><img class="card-img-top" src="https://images.unsplash.com/photo-1552913903-2cffa1962dc7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="German food"></a>
    <div class="card-body">
      <h5 class="card-title">German</h5>
      <p class="card-text">German cuisine is so much more than just sausage and meat. There's sauerkraut too!</p>
    </div>
  </div>
    </div>
  </div>
</div>

app/views/cuisines/show.html.erb
<h2 id="cuisine-name"><%=@cuisine.name%></h2>

<div class="container">
  <div class="row">
    <% @cuisine.restaurants.each do |restaurant| %>
    <%if restaurant.items.count > 0 %>
      <div id="cuisine-cards" class="card">
        <%= link_to image_tag("https://loremflickr.com/#{restaurant.img_url}", :size => '300x200'), restaurant_path(restaurant) %>
        <div class="card-body">
          <h4 id="restaurant-names"><%=restaurant.name%></h4>
        </div>
      </div>
      <%end %>
    <% end %>
  </div>
<a href = '/'><button type="button" class="btn btn-danger btn-md back-button">Back to Home</button></a>
</div>

app/views/orders/confirmation.html.erb
<div id="order-confirmation">
  <h1>Your order is on its way!</h1>

  <h3> Receipt for Order No. <%= @order.id %></h3>
  <br>
  <div id="order-wrapper">
    <% if @order_items.any? %>
        <% @order_items.each do |i| %>
          <p><%= i.item.name %> |
          
          Unit Price: <%= number_to_currency i.item.price %> | Quantity: <%= i.quantity %></p>
        <% end %>
      <%cart_total = 0 %>
        <%@order_items.each do |i|%>
          <%cart_total = cart_total + i.item.price * i.quantity.to_i%>
        <%end%>
          <font size = 4>Order Total: <%=number_to_currency cart_total%></font>
        <% else %>
          <p>Your shopping cart is empty.</p>
    <% end %>
    <br>
    <br>
  <a href = '/'><button type="button" class="btn btn-danger btn-md">Go Home</button></a>

</div>

app/views/orders/show.html.erb
<div id="order-confirmation">
  <h1>Your order is on its way!</h1>

  <h3> Receipt for Order No. <%= @order.id %></h3>
  <br>
  <div id="order-wrapper">
    <% if @order_items.any? %>
        <% @order_items.each do |i| %>
          <p><%= i.item.name %> |
          
          Unit Price: <%= number_to_currency i.item.price %> | Quantity: <%= i.quantity %></p>
        <% end %>
      <%cart_total = 0 %>
        <%@order_items.each do |i|%>
          <%cart_total = cart_total + i.item.price * i.quantity.to_i%>
        <%end%>
          <font size = 4>Order Total: <%=number_to_currency cart_total%></font>
        <% else %>
          <p>Your shopping cart is empty.</p>
    <% end %>
    <br>
    <br>
  <a href = '/'><button type="button" class="btn btn-danger btn-md">Go Home</button></a>

</div>

app/views/restaurants/show.html.erb
<% if flash[:success] %>
    <div class="alert alert-warning" role="alert">
        <div class="notice"><%= flash[:success] %></div>
    </div>
<% end %>

<div id="restaurant-wrapper">
  <% @restaurant.items.each do |item| %>
    <p><span id="item-names"><%= item.name %></span>  <span id="item-price"><%= number_to_currency item.price %></span></p>
    <br>
    <p id="item-description"><%= item.description %></p>
      <div id="item-quantity">
        <%= form_for @order_item do |f| %>
          <%= f.hidden_field :item_id, value: item.id %>
          
          
          <%= f.label :quantity, "Add Quantity:" %>
          <%= f.number_field :quantity, min: 0 %>
          <%= f.submit "Add to cart", class: "btn btn-danger btn-md float-button"%>
          <hr>
        <% end %></p>
      </div>
  <% end %>
<a href = '/cart'><button type="button" class="btn btn-danger btn-md center-button">Go to My Cart</button></a>
</div>
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 <script>

app/views/users/edit.html.erb
<% if flash[:errors] %>
    <div class="alert alert-danger" role="alert">
        <%flash[:errors].each do |message| %>
        <div class="notice"><%=message%></div>
        <%end %>
    </div>
<% end %>

<!--
<%= form_for @user do |f| %>
    <%= f.label 'Full name: '%>
    <%= f.text_field :name %><br>
    <%= f.label 'Edit a username: '%>
    <%= f.text_field :username %><br>
    <%= f.label 'Edit a password: '%>
    <%= f.password_field :password %><br>
    <%= f.label 'Confirm password: '%>
    <%= f.password_field :password_confirmation %><br>
    <%= f.label 'Delivery address: '%>
    <%= f.text_field :address %><br>
    <%= f.label 'Email address: '%>
    <%= f.email_field :email %><br>
    <%= f.label 'Phone number: '%>
    <%= f.phone_field :phone_number %><br>
    <button type="submit" class="btn btn-danger">Update</button>
<% end %>
-->

<br>


<form action="/users" name="myForm" method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<div class="container-fluid">
		<div class="row">
			<div class="well center-block">
				<div class="well-header">
					<h3 class="text-center text-danger"> Edit your account </h3>
					<hr>
				</div>

				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-user"></i>
								</div>
								<input type="text" value="<%=@user.name %>" placeholder="Full Name" class="form-control" id="name" name="user[name]">	
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-user"></i>
								</div>
								<input type="text" value="<%=@user.username %>" placeholder="Username" class="form-control" id="username" name="user[username]">
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-lock"></i>
								</div>
								<input type="password" minlength="8" maxlength="20" value="<%=@user.password %>" placeholder="Password" class="form-control" id="password" name="user[password]">
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-lock"></i>
								</div>
								<input type="password" minlength="8" maxlength="20" value="<%=@user.password_confirmation %>" placeholder="Confirm Password" class="form-control" id="password_confirmation" name="user[password_confirmation]">
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 col-xs-12 col-sm-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-list-alt"></i>
								</div>
								<textarea class="form-control" value="<%=@user.address %>" value="<%=@user.address %>" placeholder="Delivery Address" id="address" name="user[address]"></textarea>
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 col-xs-12 col-sm-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-envelope"></i>
								</div>
								<input type="email" class="form-control" value="<%=@user.email %>" placeholder="E-Mail" id="email" name="user[email]">
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 col-xs-12 col-sm-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-phone"></i>
								</div>
								<input type="number" minlength="10" maxlength="12" class="form-control" value="<%=@user.phone_number %>" placeholder="Phone Number" id="phone_number" name="user[phone_number]">
							</div>
						</div>
					</div>
				</div>

				<div class="row widget">
					<div class="col-md-12 col-xs-12 col-sm-12">
						<button type="submit" class="btn btn-danger btn-block"> Edit Account </button>
					</div>
				</div>
			</div>
		</div>
	</div>


</form>

app/views/users/new.html.erb
<!-- <h1>Sign up for GrubCRUD</h1>
<br> -->

<% if flash[:message] %>
    <div class="alert alert-danger" role="alert">
        <%flash[:message].each do |message| %>
        <div class="notice"><%=message%></div>
        <%end %>
    </div>
<% end %>

<!--
<%= form_for @user do |f| %>
    <%= f.label 'Full name: '%>
    <%= f.text_field :name %><br>
    <%= f.label 'Create a username: '%>
    <%= f.text_field :username %><br>
    <%= f.label 'Create a password: '%>
    <%= f.password_field :password %><br>
    <%= f.label 'Confirm password: '%>
    <%= f.password_field :password_confirmation %><br>
    <%= f.label 'Delivery address: '%>
    <%= f.text_field :address %><br>
    <%= f.label 'Email address: '%>
    <%= f.email_field :email %><br>
    <%= f.label 'Phone number: '%>
    <%= f.phone_field :phone_number %><br>
    <button type="submit" class="btn btn-danger">Sign up</button>
<% end %>
-->

<form action="/users" name="myForm" method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<div class="container-fluid">
		<div class="row">
			<div class="well center-block">
				<div class="well-header">
					<h3 class="text-center text-danger"> Sign up for GrubCRUD </h3>
					<hr>
				</div>

				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-user"></i>
								</div>
								<input type="text" placeholder="Full Name" class="form-control" id="name" name="user[name]">	
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-user"></i>
								</div>
								<input type="text" placeholder="Username" class="form-control" id="username" name="user[username]">
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-lock"></i>
								</div>
								<input type="password" minlength="8" maxlength="20" placeholder="Password" class="form-control" id="password" name="user[password]">
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-lock"></i>
								</div>
								<input type="password" minlength="8" maxlength="20" placeholder="Confirm Password" class="form-control" id="password_confirmation" name="user[password_confirmation]">
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 col-xs-12 col-sm-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-list-alt"></i>
								</div>
								<textarea class="form-control" placeholder="Delivery Address" id="address" name="user[address]"></textarea>
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 col-xs-12 col-sm-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-envelope"></i>
								</div>
								<input type="email" class="form-control" placeholder="E-Mail" id="email" name="user[email]">
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12 col-xs-12 col-sm-12">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="glyphicon glyphicon-phone"></i>
								</div>
								<input type="number" minlength="10" maxlength="12" class="form-control" placeholder="Phone Number" id="phone_number" name="user[phone_number]">
							</div>
						</div>
					</div>
				</div>

				<div class="row widget">
					<div class="col-md-12 col-xs-12 col-sm-12">
						<button type="submit" class="btn btn-danger btn-block"> Register </button>
					</div>
				</div>
			</div>
		</div>
	</div>


</form>

app/views/users/show.html.erb
<div class="profile-container">
  <h1>Hey, <%=@current_user.name.capitalize%>!</h1>
  <br>
  <h3>Your order history:</h3>
    <%if @current_user.orders.count > 0%>
        <%@current_user.orders.each do |order|%>
           <%=link_to order.viewable, order_path(order)%>
          <%=order.created_at.strftime("%b %d, %Y")%>
          <%cart_total = 0 %>
          <%order.order_items.each do |i|%>
              <%cart_total = cart_total + i.item.price * i.quantity.to_i%>
          <%end%>
        Order Total: <%=number_to_currency cart_total%><br>
      <%end%>
    <%else %>
      <%="You have not placed any orders yet."%>
      <br>
    <%end %>
  <br>
  <div id="button-container">
    <button type="button" class="btn btn-danger btn-sm"><a href = '/users/<%=@current_user.id%>/edit'>Edit My Details</a></button>

    <button type="button" class="btn btn-danger btn-sm"><%= link_to "Delete My Account", @current_user, :data => {:confirm => "Are you sure?", :method => "delete", class: 'delete-button float-button'} %></button>
  </div>
</div>