config/routes.rb
Rails.application.routes.draw do
  root "cuisines#index"
  resources :order_items
  resources :cuisines, only: [:index, :show]
  resources :restaurants
  resources :items
  resources :orders
  resources :users
  resource :cart, only: [:show]
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get "/secretapology", to: "sessions#absolve", as: "absolve"
  get '/orders/:id/confirmation', to: 'orders#confirmation', as: 'confirmation'
  delete "/logout", to: "sessions#destroy", as: "logout"
  delete "/clearcart", to: "carts#destroy", as: "clear_cart"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :restaurants
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  def viewable
    "Order No. #{self.id}"
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates :quantity, numericality: {greater_than: 0}

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :cuisine
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
    has_many :orders, dependent: :destroy
    validates_presence_of :username
    validates_presence_of :address
    validates_presence_of :email
    validates_presence_of :phone_number
    # validates_uniqueness_of :phone_number
    validates_uniqueness_of :username

    has_secure_password
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end

  def destroy
    session.delete :order_id
    redirect_to cart_path
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

  def index
    @cuisines = Cuisine.all
  end

  def show 
    @cuisine = Cuisine.find(params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
   
    def index
        restaurant = Restaurant.find_by(id: params[:id])
        @items = Item.where(restaurant_id: restaurant)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_items = current_order.order_items
  end

  def confirmation
    @order = Order.find(params[:id])
    @order_items = current_order.order_items
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ApplicationHelper

  def new
    if logged_in?
      redirect_to @current_user
    end
  end
#everytime we log in we create new user and order session
  def create
    session[:incorrect_count] ||= 0
    username = params[:username]
    password = params[:password]
    user = User.find_by(username: username)
      if user && user.authenticate(password)
        session[:user_id] = user.id
        order = Order.create(user_id: session[:user_id], status: false)
        session[:order_id] = order.id
        redirect_to root_path
      else
    flash[:message] = "Incorrect username or password. Please try again."
    session[:incorrect_count] += 1
      if session[:incorrect_count] >= 100
        session[:lockout] = "You have exceeded your number of login attempts!"
      end
    redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    session.delete(:order_id)
    redirect_to root_path
  end

  def absolve
    session[:lockout] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:message] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end
  
  def edit
    find_user
  end

  def update
    find_user
    if @user.update(user_params)
      flash[:message] = "Your account has been successfully updated."
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def show
    redirect_to login_path and return if !logged_in?

    if current_user.id != params[:id].to_i
      redirect_to current_user
    end

  end

  def destroy
    find_user
    @user.destroy
    session.delete :user_id
    flash[:notice] = "User deleted"
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation, :address, :email, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end    
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
​
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Kreon:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Concert+One&display=swap" rel="stylesheet">
  </head>
​
  <body>

    <nav id="navbar" class="navbar navbar-expand-lg sticky-top navbar-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <% if logged_in? %>
            <%= link_to "Home", root_path, class: "red-hover nav-item nav-link active"%>
            <%= link_to "My Cart", cart_path, class: "red-hover nav-item nav-link"%>
            <%= link_to "My Account", user_path(session[:user_id]), class: "red-hover nav-item nav-link"%>
            <%= link_to "Logout", logout_path, method: :delete, class: "red-hover nav-item nav-link" %>
          <% else %>
            <%= link_to "Home", root_path, class: "red-hover nav-item nav-link active"%>
            <%= link_to "Log In", login_path, class: "red-hover nav-item nav-link" %><br>
            <%= link_to 'Sign Up', new_user_path, class: "red-hover nav-item nav-link" %><br>
          <% end %>
        </div>
      </div>
    </nav>


      <!-- Jumbotron -->
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 id="grubcrud" class="display-4">GrubCRUD</h1>
        <p id="slogan" class="lead">Put our food in your face</p>
      </div>
    </div>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script>
        $(document).ready(function(){       
          var scroll_pos = 0;
          $(document).scroll(function() { 
          let nav = $('#navbar');
          let wait = $('#navbar').height();
          nav.toggleClass("scrolled", $(this).scrollTop() > wait);
          });
        });  
      </script>
  
  </body>
</html>